spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://193.112.251.82:3307/topshow?useSSL=false
    username: topshow
    password: 2ydHyeNjTy5EOwgG
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    port: 6380
    host: 193.112.251.82
    password: q7FIqKnrILC98sTeb2Z2
    database: 15
    timeout: 5000ms

swagger:
  show: true